name: Java CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build plugin
        run: |
          chmod +x gradlew
          ./gradlew jar
      - name: Upload jar
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/TheInspection.jar
          tag: ${{ github.ref }}
